// App module
export const APP_SET_TITLE_BAR = 'APP_SET_TITLE_BAR'

// Auth module
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE'

export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const AUTH_SET_PROFILE = 'AUTH_SET_PROFILE'

// Wallet module
export const WALLET_CREATE = 'WALLET_CREATE'
export const WALLET_CREATING = 'WALLET_CREATING'
export const WALLET_CREATE_SUCCESS = 'WALLET_CREATE_SUCCESS'
export const WALLET_CREATE_FAILURE = 'WALLET_CREATE_FAILURE'
export const WALLET_ADD_MONEY = 'WALLET_ADD_MONEY'
export const WALLET_RESET_STATE_ON_CREATE = ''
export const WALLET_ADD_TRANSACTION = 'WALLET_ADD_TRANSACTION'
