version: '3'

services:
  smyserverdev:
      build:
        context: .
        dockerfile: Dockerfile-dev
      expose:
        - '3000'
      ports:
        - '3000:3000' 
      working_dir: /data
      volumes:
        - "./:/data"
  mongodev:
    image: mongo:3.4
    volumes:
      - "./temp/mongo:/data/db"
